       IDENTIFICATION DIVISION.
       PROGRAM-ID. STRLEFT.

       ENVIRONMENT DIVISION.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01   WS-INDEX                PIC 9(9) COMP-5.

       LINKAGE SECTION.
       01   LS-STRLEFT-STR1         PIC X(255).
       01   LS-STRLEFT-STR1-LEN     PIC 9(9) COMP-5.
       01   LS-STRLEFT-RETURN       PIC X(255).
       01   LS-STRLEFT-RETURN-LEN   PIC 9(9) COMP-5.
       01   LS-STRLEFT-AMOUNT       PIC 9(9) COMP-5.

       PROCEDURE DIVISION USING LS-STRLEFT-STR1 LS-STRLEFT-STR1-LEN
           LS-STRLEFT-AMOUNT LS-STRLEFT-RETURN LS-STRLEFT-RETURN-LEN.

           MOVE 1 TO WS-INDEX
           MOVE ALL SPACES TO LS-STRLEFT-RETURN(1:LS-STRLEFT-RETURN-LEN)
           PERFORM UNTIL WS-INDEX > LS-STRLEFT-AMOUNT OR
           -    WS-INDEX > LS-STRLEFT-STR1-LEN
               MOVE LS-STRLEFT-STR1(WS-INDEX:1) TO
                   LS-STRLEFT-RETURN(WS-INDEX:1)
               ADD 1 TO WS-INDEX
           END-PERFORM
           GOBACK.
